// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhcikscgofkhzzjyqexg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloY2lrc2Nnb2ZraHp6anlxZXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzQ4NDQsImV4cCI6MjA3MTAxMDg0NH0.3yt4iG6eEWldaQV7mf4usLMTjPMBfHe8mxAgo07dnVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});